### ISSUE TITLE
Support Everybody Gets One bill target counts for beddings

### ISSUE THREAD

**Issue by ZzZombo** [jptrrs/SoftWarmBeds#12]
Currently, you can't use Everybody Gets One to make beddings for each colonist using its features. Once a bed is made, it no longer exists as far as I'm aware, so bills lose track of them. However, with "Count equipped" enabled, bills should keep track of items produced.

**Comment by jptrrs** [comment]
The bedding is not something that can be equipped by a colonist, so of course the bills can't track it that way. :-)
What you suggest would take changes to Everybody Gets One, not Soft Warm Beds.
